### ISSUE TITLE
[Android Sample] java.lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$drawable"

### ISSUE THREAD

**Issue by robertoestivill** [gildor/kotlin-coroutines-android#4]
Just cloned the repo, tried to run the sample and it crashes on app launch.
Cheers

Motorola Moto X 2nd GEN 2014
XT1095 - 6.0

```
06-20 10:58:27.413 15706 15706 D AndroidRuntime: Shutting down VM
06-20 10:58:27.419 15706 15706 E AndroidRuntime: FATAL EXCEPTION: main
06-20 10:58:27.419 15706 15706 E AndroidRuntime: Process: ru.gildor.coroutines.android.sample, PID: 15706
06-20 10:58:27.419 15706 15706 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable;
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:111)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:33)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:203)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at ru.gildor.coroutines.android.sample.MainActivity.onCreate(MainActivity.kt:33)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6245)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$drawable" on path: DexPathList[[zip file "/data/app/ru.gildor.coroutines.android.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.gildor.coroutines.android.sample-1/lib/arm, /vendor/lib, /system/lib]]
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	... 24 more
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: android.support.v7.appcompat.R$drawable
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		... 25 more
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-20 10:58:27.421  1770  2514 W ActivityManager:   Force finishing activity ru.gildor.coroutines.android.sample/.MainActivity06-20 10:58:27.413 15706 15706 D AndroidRuntime: Shutting down VM
06-20 10:58:27.419 15706 15706 E AndroidRuntime: FATAL EXCEPTION: main
06-20 10:58:27.419 15706 15706 E AndroidRuntime: Process: ru.gildor.coroutines.android.sample, PID: 15706
06-20 10:58:27.419 15706 15706 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable;
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:111)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:151)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:33)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:203)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at ru.gildor.coroutines.android.sample.MainActivity.onCreate(MainActivity.kt:33)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6245)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$drawable" on path: DexPathList[[zip file "/data/app/ru.gildor.coroutines.android.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/ru.gildor.coroutines.android.sample-1/lib/arm, /vendor/lib, /system/lib]]
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	... 24 more
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: android.support.v7.appcompat.R$drawable
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 		... 25 more
06-20 10:58:27.419 15706 15706 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-20 10:58:27.421  1770  2514 W ActivityManager:   Force finishing activity ru.gildor.coroutines.android.sample/.MainActivity
```

**Comment by khalid64927** [comment]
change version as below, but this still leaves with one compiler issue for onCompletion method ( continuation.onCompletion ).


ext.kotlin_version = '1.1.51'
ext.kotlin_coroutines_version = '0.19.1'

**Comment by khalid64927** [comment]
ok the method onCompletion is not there replace it with invokeOnCompletion
